name: Check Video Codec

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_codec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Check video codec
        run: |
          ffmpeg -i video.mp4
